name: RSpec / System Spec

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: Beauty_BA_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install System Dependencies (Chrome for System Spec)
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips-dev google-chrome-stable

      - name: Build Assets
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails assets:precompile

      - name: Set up Database
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/Beauty_BA_test
        run: |
          bundle exec rails db:prepare

      - name: Run RSpec
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/Beauty_BA_test
        run: |
          bundle exec rspec

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: capybara-screenshots
          path: tmp/capybara/